name: mdown
version: 0.13.0+dev
description: Fast CommonMark-compliant markdown parser
author: Maxim Dikun <dikmax@gmail.com>
homepage: https://github.com/dikmax/mdown
environment:
  sdk: ">=2.3.0 <3.0.0"
dependencies:
dev_dependencies:
  build: '^1.1.4'
  build_config: '^0.4.0'
  build_runner: '^1.6.1'
  coverage: '^0.12.4'
  test: '^1.6.4'
  source_gen: '^0.9.0'
