name: markdowntypography
version: 0.0.1
description: Markdown typography processor
dependencies:
  collection: any
  unicode_helper: any
  parsers:
    path: /Users/dikmax/workspace/parsers
dev_dependencies:
  unittest: any
