name: md_proc
version: 0.9.0+1
description: Fast CommonMark-compliant markdown parser
author: Maxim Dikun <dikmax@gmail.com>
homepage: https://github.com/dikmax/md_proc
environment:
  sdk: ">=1.18.0 <2.0.0"
dependencies:
  collection: '>=1.9.0 <2.0.0'
  quiver: "^0.22.0"
dev_dependencies:
  benchmark_harness: any
  test: any
  linter: any
  dart_coveralls: any
  source_gen: '>=0.5.0 <0.6.0'
