name: md_proc
version: 0.7.5
description: CommonMark-compliant markdown parser
author: Maxim Dikun <dikmax@gmail.com>
homepage: https://github.com/dikmax/md_proc
environment:
  sdk: ">=1.9.0 <2.0.0"
dependencies:
  collection: '>=1.0.0 <2.0.0'
  parsers: '>=0.14.5 <0.15.0'
  quiver: "^0.21.4"
dev_dependencies:
  benchmark_harness: any
  markdown: '>=0.9.0 <1.0.0'
  test: any
  linter: any
  dart_coveralls: any
  source_gen: '>=0.4.2 <0.5.0'
