name: md-proc
version: 0.1.0
description: CommonMark-compliant markdown parser
author: Maxim Dikun <dikmax@gmail.com>
dependencies:
  collection: any
  unicode_helper: any
  parsers: '>=0.14.3 <0.15.0'
dev_dependencies:
  unittest: any
r
