name: md_proc
version: 0.10.3
description: Obsolete package. Superseeded by mdown.
author: Maxim Dikun <dikmax@gmail.com>
homepage: https://github.com/dikmax/mdown
environment:
  sdk: ">=1.18.0 <2.0.0"
dependencies:
  collection: '>=1.9.0 <2.0.0'
  quiver: "^0.24.0"
dev_dependencies:
  benchmark_harness: '1.0.4'
  build_runner: '^0.1.1'
  coverage: '^0.8.0+2'
  markdown: any
  test: '^0.12.17+2'
  source_gen: '>=0.5.2 <0.6.0'
